import unittest
from tests.test_execute_builder_cmd import TestExecute_builder_cmd
from tests.test_execute_builder_cmd import TestExecute_builder_cmd_init_fail
from tests.test_execute_builder_cmd import TestExecute_builder_cmd_init_done
# from tests.test_execute_builder_cmd import TestExecute_builder_cmd_init_done_with_destination
# from tests.test_execute_builder_cmd import TestExecute_builder_cmd_init_done_with_description
from tests.test_execute_builder_cmd import TestExecute_builder_cmd_db_init_fail


if __name__ == '__main__':

    unittest.main()
