# coding= utf-8

MISSING_PROJECT_NAME = 1
MISSING_PROJECT_DESTINATION = 2
MISSING_SOURCE_DIRECTORY = 3
PROJECT_DIRECTORY_ALREADY_EXISTS = 4
PROJECT_DIRECTORY_PERMISSION_ERROR = 5
DATABASE_CONFIGURATION_ERROR = 6
MISSING_PROJECT_CONFIGURATION = 7
MISSING_DATABASE_CONFIGURATION = 8
MISSING_DATABASE_TYPE = 9
TABLE_NOT_PRESENT = 10
MISSING_ORM_MODELS = 11
DATABASE_NOT_CONFIGURED = 12
DATABASE_INITIALIZATION_ERROR = 13
DATABASE_CONNECTION_ERROR = 14
FILE_ALREADY_EXISTS = 15
FILE_PERMISSION_ERROR = 16
BASE_COMPONENT_NOT_EXISTS= 17

lmap = {}
lmap[MISSING_PROJECT_NAME] = 'MISSING_PROJECT_NAME'
lmap[MISSING_PROJECT_DESTINATION] = 'MISSING_PROJECT_DESTINATION'
lmap[MISSING_SOURCE_DIRECTORY] = 'MISSING_SOURCE_DIRECTORY'
lmap[PROJECT_DIRECTORY_ALREADY_EXISTS] = 'PROJECT_DIRECTORY_ALREADY_EXISTS'
lmap[PROJECT_DIRECTORY_PERMISSION_ERROR] = 'PROJECT_DIRECTORY_PERMISSION_ERROR'
lmap[DATABASE_CONFIGURATION_ERROR] = 'DATABASE_CONFIGURATION_ERROR'
lmap[MISSING_PROJECT_CONFIGURATION] = 'MISSING_PROJECT_CONFIGURATION'
lmap[MISSING_DATABASE_CONFIGURATION] = 'MISSING_DATABASE_CONFIGURATION'
lmap[MISSING_DATABASE_TYPE] = 'MISSING_DATABASE_TYPE'
lmap[TABLE_NOT_PRESENT] = 'TABLE_NOT_PRESENT'
lmap[MISSING_ORM_MODELS] = 'MISSING_ORM_MODELS '
lmap[DATABASE_NOT_CONFIGURED] = 'DATABASE_NOT_CONFIGURED'
lmap[DATABASE_INITIALIZATION_ERROR] = 'DATABASE_INITIALIZATION_ERROR'
lmap[DATABASE_CONNECTION_ERROR] = 'DATABASE_CONNECTION_ERROR'
lmap[FILE_ALREADY_EXISTS] = 'FILE_ALREADY_EXISTS'
lmap[FILE_PERMISSION_ERROR] = 'FILE_PERMISSION_ERROR'
lmap[BASE_COMPONENT_NOT_EXISTS] = 'BASE_COMPONENT_NOT_EXISTS'

lrev = {}
for k in lmap:
    lrev[lmap[k]] = k

